repositories:
  - name: starwitorg
    url: registry-1.docker.io/starwitorg
    oci: true
  - name: bitnamicharts
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: starwit-internal
    url: https://helm.internal.starwit-infra.de
    username: chartmuseum
    password: {{ requiredEnv "HELM_SECRET" }}

helmDefaults:
  wait: true

environments:
  default:
    values:
      - namespace: anomaly-detection
        redis:
          host: test-redis-master.sae
          port: 6379
        minio:
          user: minioadmin
          password: {{ requiredEnv "MINIO_PASSWORD" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }}
  local:
    values:
      - namespace: anomaly-detection
        redis:
          host: 192.168.178.66
          port: 6379
        minio:
          user: minioadmin
          password: {{ requiredEnv "MINIO_PASSWORD" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }}

---
releases:
  - name: minio
    namespace: {{ .Values.namespace }}
    chart: oci://registry-1.docker.io/bitnamicharts/minio
    installed: true
    version: "14.8.5"  
    values:
      - auth:
          rootUser: {{ .Values.minio.user }}
          rootPassword: {{ .Values.minio.password }}
        ingress:
          enabled: false
        defaultBuckets: anomalies

  - name: anomaly-post-processing
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/anomaly-post-processing
    version: 3.0.0
    values:
      - config:
          log_level: INFO
          minio:
            endpoint: "minio:9000"
            user: {{ .Values.minio.user }}
            password: {{ .Values.minio.password }}
            secure: false
            bucket_name: anomalies
          redis_input:
            host: {{ .Values.redis.host }}
            port: {{ .Values.redis.port }}
            stream_ids: 
              - RangelineSMedicalDr
            stream_prefix: anomalydetection
          redis_output: null
          raw_anomalies: true
        pullSecret:
          registry: docker.internal.starwit-infra.de
          username: docker
          password: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry

  - name: sae-anomaly-detection-rangelinesmedicaldr
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/sae-anomaly-detection
    version: 1.0.1
    values:
      - config:
          log_level: INFO
          redisIn:
            stream_id: RangelineSMedicalDr
            stream_prefix: geomapper
            host: {{ .Values.redis.host }}
            port: {{ .Values.redis.port }}
          redisOut:
            stream_id: RangelineSMedicalDr
            stream_prefix: anomalydetection
            host: {{ .Values.redis.host }}
            port: {{ .Values.redis.port }}
          filtering: True
          model:
            parameters_path: model/parameters.json
            weights_path: model/model_weights.pth
            background_path: model/frame.pth
        useGpu: true
        weights:
          imageTag: cnnsymmetricprob-rangelinesmedicaldr-20250409
        existingPullSecret: anomaly-post-processing-pull-secret