repositories:
  - name: starwitorg
    url: registry-1.docker.io/starwitorg
    oci: true
  - name: bitnamicharts
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: starwit-internal
    url: https://helm.internal.starwit-infra.de
    username: chartmuseum
    password: {{ requiredEnv "HELM_SECRET" }}

helmDefaults:
  wait: true

environments:
  default:
    values:
      - namespace: temp
        hostname: messe-demo.local
        minio:
          user: minioadmin
          password: minioadmin
        pullSecret: {{ requiredEnv "PULL_SECRET" }}
  hannover-demo:
    values:
      - namespace: aic
        hostname: aic.dev-laptop01
        minio:
          user: minioadmin
          password: minioadmin
        pullSecret: {{ requiredEnv "PULL_SECRET" }}

---
releases:
  - name: aicockpit 
    namespace: {{ .Values.namespace }}
    chart: starwitorg/ai-cockpit-chart
    version: "1.0.1-1"
    values:
      - image:
          tag: "1.0.1-1-kic"
      - app:
          context_path: ""
        postgresql:
          auth:
            database: aicockpit
            username: aicockpit
            password: aicockpit
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: cockpit.{{ .Values.hostname }}
              paths:
                - path: "/"
                  pathType: ImplementationSpecific
        minio:
          user: {{ .Values.minio.user }}
          password: {{ .Values.minio.password }}
          endpoint: http://minio.{{ .Values.namespace }}.svc.cluster.local:9000
        sampledata:
          enabled: true
          image: starwitorg/ai-cockpit-sampledata:250429-test
          importFolder: traffic
          language: en
        aiapi:
          transparency:
            enabled: true
            uri: http://transparency-api-starwit-aicapi-transparency-chart.{{ .Values.namespace }}.svc.cluster.local:8080
        sbom:
          enabled: true
          generator:
            uri: http://sbom-generator-sbom-generator-chart.{{ .Values.namespace }}.svc.cluster.local:8080
        extraEnv: |
          - name: DECISION_TYPE_DEFAULT
            value: "dangerous driving behaviour"
          - name: SPRING_AUTOCONFIGURE_EXCLUDE
            value: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
          - name: DECISION_TYPE_RANDOM
            value: "true"

  - name: minio
    namespace: {{ .Values.namespace }}
    chart: oci://registry-1.docker.io/bitnamicharts/minio
    installed: true
    version: "14.8.5"  
    values:
      - auth:
          rootUser: {{ .Values.minio.user }}
          rootPassword: {{ .Values.minio.password }}
      - ingress:
          enabled: true
          hostname: minio.{{ .Values.hostname }}
          tls: false

  - name: anomaly-post-processing
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/anomaly-post-processing
    version: 4.0.0
    values:
      - config:
          log_level: DEBUG
          raw_anomalies: false
          http_output:
            target_endpoint: http://ai-cockpit:8081/api/aic/decision
            module_name: Anomaly Detection
            decision_type_name: dangerous driving behaviour
            minio:
              user: {{ .Values.minio.user }}
              password: {{ .Values.minio.password }}
              endpoint: minio:9000
              secure: false
              bucket_name: anomalies
          redis_input:
            host: valkey-primary
            port: 6379
            stream_ids: 
              - medical
              - citycenter
            stream_prefix: anomalydetection
        existingPullSecret: internal-docker-registry

  - name: valkey
    installed: true
    namespace: {{ .Values.namespace }}
    chart: bitnamicharts/valkey
    version: 2.2.0
    values:
      - architecture: standalone
        primary:
          persistence:
            enabled: false
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 200m
        auth:
          enabled: false
        commonConfiguration: |
          save ""
          appendonly no

  - name: sae-dump-player
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/sae-dump-player-chart
    version: 0.2.0
    values:
      - config:
          redisHost: valkey-primary
          redisPort: 6379

  - name: anomaly-detection-legacy-medical
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/anomaly-detection-legacy
    version: 4.2.1
    values:
      - imageCredentials:
          registry: docker.internal.starwit-infra.de
          username: docker
          password: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry
        extraEnv:
          - name: SIGNIFICANT_MOVEMENT
            value: "0.004"
          - name: REDIS_HOST
            value: valkey-primary
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_STREAM_IDS
            value: medical
          - name: REDIS_INPUT_STREAM_PREFIX
            value: geomapper
          - name: REDIS_OUTPUT_STREAM_PREFIX
            value: anomalydetection
          - name: PATH_TO_MODEL_JSON
            value: models/RangelineSMedicalDr_2024-04-22.json
          - name: ANOMALY_THRESHOLD
            value: "0.00005"
          - name: ANOMALY_POSITION_ENABLED
            value: "true"
          - name: MAX_Z_SCORE
            value: "10"
          - name: STORE_WHOLE_VIDEO
            value: "false"
          - name: ENABLE_LOCAL_OUTPUT
            value: "false"
          - name: ENABLE_REDIS_OUTPUT
            value: "true"

  - name: anomaly-detection-legacy-citycenter
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/anomaly-detection-legacy
    version: 4.2.1
    values:
      - extraImagePullSecrets:
        - name: internal-docker-registry
        extraEnv:
          - name: SIGNIFICANT_MOVEMENT
            value: "0.004"
          - name: REDIS_HOST
            value: valkey-primary
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_STREAM_IDS
            value: citycenter
          - name: REDIS_INPUT_STREAM_PREFIX
            value: geomapper
          - name: REDIS_OUTPUT_STREAM_PREFIX
            value: anomalydetection
          - name: PATH_TO_MODEL_JSON
            value: models/RangelineCityCenterSB_2024-11-28.json
          - name: ANOMALY_THRESHOLD
            value: "0.00005"
          - name: ANOMALY_POSITION_ENABLED
            value: "true"
          - name: MAX_Z_SCORE
            value: "10"
          - name: STORE_WHOLE_VIDEO
            value: "false"
          - name: ENABLE_LOCAL_OUTPUT
            value: "false"
          - name: ENABLE_REDIS_OUTPUT
            value: "true"

  - name: sae-anomaly-detection
    installed: false
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/sae-anomaly-detection
    version: 0.3.2
    values:
      - config:
          log_level: DEBUG
          redisIn:
            stream_id: stream1
            host: valkey-primary
            port: 6379
          redisOut:
            stream_id: stream1
            host: 10.0.1.6
            port: 30379
        imageCredentials:
          registry: docker.internal.starwit-infra.de
          username: docker
          password: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry

  - name: sbom-generator
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/sbom-generator-chart
    version: 0.0.10

  - name: transparency-api
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/starwit-aicapi-transparency-chart
    version: 1.0.0
    values:
      - app:
          context_path: ""
          service_uri: http://transparency-api-starwit-aicapi-transparency-chart:8080
      - auth:
          enabled: false