repositories:
  - name: starwitorg
    url: registry-1.docker.io/starwitorg
    oci: true
  - name: bitnamicharts
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: starwit-internal
    url: https://helm.internal.starwit-infra.de
    username: chartmuseum
    password: {{ requiredEnv "HELM_SECRET" }}

helmDefaults:
  wait: true

environments:
  default:
    values:
      - namespace: temp
        valkey: true
  aic-dev:
    values:
      - namespace: sae
        valkey: true

---
releases:
  - name: valkey
    installed: {{ .Values.valkey }}
    namespace: {{ .Values.namespace }}
    chart: bitnamicharts/valkey
    version: 2.2.0
    values:
      - architecture: standalone
        primary:
          persistence:
            enabled: false
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 200m
        auth:
          enabled: false
        commonConfiguration: |
          save ""
          appendonly no

  - name: sae-dump-player
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/sae-dump-player-chart
    version: 0.2.0
    values:
      - config:
          redisHost: valkey-primary
          redisPort: 6379

  - name: sae-anomaly-detection
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/sae-anomaly-detection
    version: 0.3.5
    values:
      - config:
          log_level: DEBUG
          redisIn:
            host: valkey-primary
            port: 6379
            stream_id: citycenter
            stream_prefix: geomapper
          redisOut:
            host: 10.0.1.6
            port: 30379
            stream_id: stream1
            stream_prefix: anomalydetection
          filtering: True
          model:
            parameters_path: model/parameters.json
            weights_path: model/model_weights.pth
            background_path: model/frame.pth
          prometheus_port: 8000
        imageCredentials:
          registry: docker.internal.starwit-infra.de
          username: docker
          password: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry
