include: 
  - ./docker-compose-minio.yml

name: ai-cockpit

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ai-cockpit
      POSTGRES_USER: ai-cockpit
      POSTGRES_PASSWORD: ai-cockpit
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ai-cockpit']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  aicockpit:
    image: starwitorg/ai-cockpit:0.1.4
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ai-cockpit"
      SPRING_DATASOURCE_USERNAME: ai-cockpit
      SPRING_DATASOURCE_PASSWORD: ai-cockpit
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
      MINIO_ENDPOINT: http://minio1:9000
      SCENARIO_SETUP: true
    volumes:
      - demodata:/scenariodata/traffic
    ports:
      - 8080:8081

volumes:
  db:
  demodata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./scenariodata/data_structures/${scenario}