name: Create sample data container

on:
  workflow_dispatch:
    inputs:
        release-version: # id of input
          description: "override default release version e.g. with 0.1.0-1"
          required: false    

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}    
  IMAGE_NAME: ai-cockpit-sampledata
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg

jobs:
  publish_docker:
    name: "Build and publish docker"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker-compose
        file: ./docker-compose/dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:latest
